nodeLinker: node-modules

# Publish @iso-safety-signs/* packages to the public npm registry.
npmScopes:
  iso-safety-signs:
    npmRegistryServer: 'https://registry.npmjs.org/'
    npmAuthToken: '${NPM_JS_AUTH:-}'
